---
- name: Настройка файрвола
  hosts: your_target_server
  become: yes

  tasks:
    - name: Установка пакета firewalld 
      package:
        name: firewalld
        state: present

    - name: Включение сервиса firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Добавление правила разрешения доступа к порту 80 (HTTP)
      firewalld:
        service: http
        state: enabled
        permanent: yes
    - name: Добавление правила разрешения доступа к порту 9090 для Prometheus
      firewalld:
         port: 9090/tcp
         state: enabled
         permanent: yes
    - name: Добавление правила разрешения доступа к порту 8080 для Prometheus
      firewalld:
         port: 8080/tcp
         state: enabled
         permanent: yes

    - name: Добавление правила разрешения доступа к порту 8080 для Prometheus
      firewalld:
         port: 5000/tcp
         state: enabled
         permanent: yes
    - name: Добавление правила разрешения доступа к порту 443 (HTTPS)
      firewalld:
        service: https
        state: enabled
        permanent: yes

    # Добавьте дополнительные задачи для настройки других правил доступа, если необходимо

  handlers:
    - name: Перезапуск сервиса firewalld после изменений
      service:
        name: firewalld
        state: restarted
