# Используем официальный образ Python
FROM python:latest

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /usr/src/app

# Копируем файлы приложения внутрь контейнера
COPY . /usr/src/app

# Устанавливаем зависимости
RUN pip install Flask

# Команда для запуска приложения
CMD ["python", "app.py"]
# Используем официальный образ Python
FROM python:latest

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /usr/src/app

# Копируем файлы приложения внутрь контейнера
COPY . /usr/src/app

# Устанавливаем зависимости
RUN pip install Flask

# Команда для запуска приложения
CMD ["python", "app.py"]

