- hosts: your_target_server
  become: yes
  vars:
    container_count: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d
  tasks:
    - name: Установить aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Установить необходимые пакеты системы
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        update_cache: true

    - name: Добавить GPG-ключ Docker в apt
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавить репозиторий Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Обновить apt и установить docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Создать виртуальную среду
      command: python3 -m venv /root/kt_last/venv

    - name: Установить модуль Docker в виртуальной среде
      pip:
        name: docker
        virtualenv: /root/kt_last/venv

    - name: Скачать основное образ Docker
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Создать основные контейнеры
      community.docker.docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ container_count }}
