---
- name: Установка и настройка Prometheus
  hosts: your_target_server
  become: yes

  tasks:
    - name: Создание директории для конфигурационного файла Prometheus
      ansible.builtin.file:
        path: /etc/prometheus
        state: directory

    - name: Копирование конфигурационного файла Prometheus
      ansible.builtin.copy:
        src: prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        mode: 0644

    - name: Установка Prometheus
      apt:
        name: prometheus
        state: present

    - name: Запуск и активация службы Prometheus
      ansible.builtin.service:
        name: prometheus
        state: started
        enabled: yes
