version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - server

  server:
    build: ./server
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
