- name: Установка и настройка базы данных PostgreSQL
  hosts: your_target_server
  become: yes

  tasks:
    - name: Установка PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Установка дополнительных пакетов
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - postgresql-contrib  # Дополнительные утилиты PostgreSQL
        - postgresql-server-dev-all  # Разработческие файлы для создания модулей расширений PostgreSQL

    - name: Запуск и активация службы PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Создание базы данных
      postgresql_db:
        name: my_database
        state: present

    - name: Создание пользователя базы данных
      postgresql_user:
        name: my_user
        password: my_password  # Здесь указываем пароль
        db: my_database
        priv: ALL
        state: present
