---
- name: Настройка системных параметров
  hosts: your_target_server
  become: yes  # Разрешить выполнение действий с привилегиями суперпользователя

  tasks:
    # Настройка параметра vm.swappiness
    - name: Установка значения параметра vm.swappiness
      sysctl:
        name: vm.swappiness
        value: 10
        state: present
      tags: 
        - swappiness

    # Настройка параметра kernel.core_pattern
    - name: Установка значения параметра kernel.core_pattern
      sysctl:
        name: kernel.core_pattern
        value: "/var/coredumps/core-%e-%s-%u-%g-%p-%t"
        state: present
      tags:
        - core_pattern

    # Настройка параметра net.ipv4.ip_forward
    - name: Включение IP-перенаправления
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
      tags:
        - ip_forward

    # Перезагрузка sysctl
    - name: Перезагрузка sysctl
      shell: sysctl --system
      become: yes
      tags:
        - sysctl_reload
