---
- name: Управление сервисом Apache
  hosts: your_target_server
  become: yes  # Для выполнения действий с правами суперпользователя

  tasks:
    - name: Запуск сервиса Apache
      service:
        name: apache2  # Имя службы Apache на Ubuntu/Debian
        state: started  # Запустить службу

    - name: Остановка сервиса Apache
      service:
        name: apache2  # Имя службы Apache на Ubuntu/Debian
        state: stopped  # Остановить службу

    - name: Перезапуск сервиса Apache
      service:
        name: apache2  # Имя службы Apache на Ubuntu/Debian
        state: restarted  # Перезапустить службу
