---
- name: Обновление системы
  hosts: your_target_server
  become: yes  # Для выполнения действий с правами суперпользователя

  tasks:
    - name: Обновление всех пакетов
      apt:
        update_cache: yes  # Обновляем кэш пакетов
        upgrade: dist      # Обновляем все пакеты до последних версий

    - name: Перезапуск сервера
      reboot:
        reboot_timeout: 300  # Время ожидания перезапуска в секундах (опционально)
        test_command: uptime  # Команда для проверки доступности сервера после перезапуска (опционально)
      async: 1               # Запуск асинхронно (для избежания блокировки)
      poll: 0                # Не ожидать завершения перезапуска (так как мы используем асинхронный режим)
